# Generated by Django 5.2.11 on 2026-03-16 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_lists', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='readinglist',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_reading_list_name_per_user'),
        ),
    ]
